default_language_version:
  python: python3.12
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-json
      -   id: check-merge-conflict
      -   id: pretty-format-json
          args: ['--autofix']
      -   id: check-added-large-files
      -   id: debug-statements
  -   repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: [ "--profile", "black", "--filter-files" ]
  -   repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
        - id: black
  -   repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
        - id: flake8
          additional_dependencies: [flake8-bugbear, pep8-naming]
          args: [--ignore, 'B010,W503,E501,E731,W504,E203', --exclude, '.git, deployments']
  -   repo: https://github.com/commitizen-tools/commitizen
      rev: 3.6.0
      hooks:
        - id: commitizen
