"""Base Tables

Revision ID: 1726721229
Revises: 
Create Date: 2024-09-19 04:47:09.182507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1726721229'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('contact_date', sa.Date(), nullable=False),
    sa.Column('contact_notes', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('skill_name', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('team_name', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('cell_phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('address_line_1', sa.String(length=100), nullable=True),
    sa.Column('address_line_2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('home_phone', sa.String(length=12), nullable=True),
    sa.Column('work_phone', sa.String(length=12), nullable=True),
    sa.Column('ishelters_id', sa.Integer(), nullable=True),
    sa.Column('ishelters_created_by_id', sa.Integer(), nullable=True),
    sa.Column('ishelters_created_dt', sa.DateTime(), nullable=True),
    sa.Column('ishelters_category_type', sa.String(length=100), nullable=True),
    sa.Column('application_received_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_to_skill_bridge',
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], )
    )
    op.create_table('volunteer_to_team_bridge',
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer_to_team_bridge')
    op.drop_table('volunteer_to_skill_bridge')
    op.drop_table('volunteer')
    op.drop_table('team')
    op.drop_table('skill')
    op.drop_table('contact')
    # ### end Alembic commands ###
