"""Added more fields for descriptions

Revision ID: 1726767774
Revises: 1726721229
Create Date: 2024-09-19 17:42:54.794732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1726767774'
down_revision = '1726721229'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('volunteer_id', sa.Integer(), nullable=True))
    op.alter_column('contact', 'contact_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contact', 'contact_notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'contact', 'volunteer', ['volunteer_id'], ['id'])
    op.add_column('skill', sa.Column('skill_description', sa.String(length=2000), nullable=True))
    op.add_column('team', sa.Column('team_description', sa.String(length=2000), nullable=True))
    op.add_column('volunteer', sa.Column('maddie_certifications_received_date', sa.Date(), nullable=True))
    op.add_column('volunteer_to_team_bridge', sa.Column('team_lead_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_to_team_bridge', 'team_lead_flag')
    op.drop_column('volunteer', 'maddie_certifications_received_date')
    op.drop_column('team', 'team_description')
    op.drop_column('skill', 'skill_description')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.alter_column('contact', 'contact_notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contact', 'contact_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('contact', 'volunteer_id')
    # ### end Alembic commands ###
